[features]
seeds = false
[programs.devnet]
mysolanaapp = "FgCxH9xv4mhisHVAmb8RCV3JVvTFKjVUayMUpmcW1xdk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/imentus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
